version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-29-node8-alpha
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Download Dependencies
          command: ./gradlew dependencies

      - run:
          name: Run Tests
          command: ./gradlew test
